from __future__ import annotations

from copy import deepcopy
from pathlib import Path
from typing import Any

from research_data.hydration import write_json


REQUIRED_CATALOG_FIELDS = [
    "dataset_id",
    "dataset_name",
    "tier",
    "domain",
    "source_type",
    "preferred_source",
    "fallback_source",
    "cost_classification",
    "update_frequency",
    "expected_latency",
    "PIT_safe",
    "required_date_fields",
    "canonical_storage_path",
    "canonical_artifact_name",
    "validation_rules",
    "freshness_sla",
    "consuming_sleeves",
    "feature_outputs",
    "owner",
    "status",
    "deprecation_policy",
    "known_risks",
]


def _entry(
    dataset_id: str,
    dataset_name: str,
    *,
    tier: str,
    domain: str,
    source_type: str,
    preferred_source: str,
    fallback_source: str,
    cost_classification: str,
    update_frequency: str,
    expected_latency: str,
    pit_safe: str,
    required_date_fields: list[str],
    canonical_storage_path: str,
    canonical_artifact_name: str,
    validation_rules: list[str],
    freshness_sla: str,
    consuming_sleeves: list[str],
    feature_outputs: list[str],
    status: str = "PLANNED",
    deprecation_policy: str = "Require replacement parity and consumer audit before retirement.",
    known_risks: list[str] | None = None,
    fr_dh_reference: str = "FR-DH-013",
) -> dict[str, Any]:
    return {
        "dataset_id": dataset_id,
        "dataset_name": dataset_name,
        "tier": tier,
        "domain": domain,
        "source_type": source_type,
        "preferred_source": preferred_source,
        "fallback_source": fallback_source,
        "cost_classification": cost_classification,
        "update_frequency": update_frequency,
        "expected_latency": expected_latency,
        "PIT_safe": pit_safe,
        "required_date_fields": list(required_date_fields),
        "canonical_storage_path": canonical_storage_path,
        "canonical_artifact_name": canonical_artifact_name,
        "validation_rules": list(validation_rules),
        "freshness_sla": freshness_sla,
        "consuming_sleeves": list(consuming_sleeves),
        "feature_outputs": list(feature_outputs),
        "owner": "Caerus Research Data Steward (TBD)",
        "status": status,
        "deprecation_policy": deprecation_policy,
        "known_risks": list(known_risks or []),
        "fr_dh_reference": fr_dh_reference,
    }


_CATALOG: list[dict[str, Any]] = [
    _entry(
        "ohlcv_prices",
        "OHLCV prices",
        tier="Tier 1",
        domain="prices",
        source_type="market_data",
        preferred_source="free/public first; existing configured market-data credentials second",
        fallback_source="Alpaca/Polygon/Nasdaq Data Link if configured",
        cost_classification="existing/free_or_paid_tbd",
        update_frequency="daily",
        expected_latency="T+0/T+1 by source",
        pit_safe="yes, if as-of dated",
        required_date_fields=["trade_date", "as_of_date", "ingestion_timestamp"],
        canonical_storage_path="data/normalized/prices/",
        canonical_artifact_name="ohlcv_prices.parquet",
        validation_rules=["schema", "duplicate_keys", "missing_bars", "stale_dates"],
        freshness_sla="next trading day",
        consuming_sleeves=["Polaris", "Orion", "Lyra", "Phoenix", "all backtests"],
        feature_outputs=["returns", "liquidity", "volatility"],
        status="OBSERVE_ONLY",
        known_risks=["stale prices", "adjustment drift", "delisted coverage gaps"],
    ),
    _entry(
        "security_master_pit",
        "Point-in-time security master",
        tier="Tier 1",
        domain="identity",
        source_type="security_master",
        preferred_source="SEC company tickers plus source-agnostic canonical master",
        fallback_source="Alpaca/Nasdaq Data Link if configured",
        cost_classification="existing/free_or_paid_tbd",
        update_frequency="daily/weekly by source",
        expected_latency="T+1 or source cadence",
        pit_safe="yes",
        required_date_fields=["as_of_date", "effective_date", "ingestion_timestamp"],
        canonical_storage_path="data/normalized/security_master/",
        canonical_artifact_name="security_master.parquet",
        validation_rules=["identifier_uniqueness", "symbol_history", "delisting_visibility"],
        freshness_sla="one business day after source refresh",
        consuming_sleeves=["all sleeves"],
        feature_outputs=["canonical_ids", "universe_joins"],
        status="OBSERVE_ONLY",
        known_risks=["survivorship bias", "reused tickers", "missing delistings"],
    ),
    _entry(
        "corporate_actions",
        "Corporate actions",
        tier="Tier 1",
        domain="corporate_actions",
        source_type="market_reference",
        preferred_source="free/public source if available",
        fallback_source="Nasdaq Data Link/Polygon if configured",
        cost_classification="existing/free_or_paid_tbd",
        update_frequency="daily",
        expected_latency="T+1 by source",
        pit_safe="yes, if knowable dates exist",
        required_date_fields=["effective_date", "as_of_date", "ingestion_timestamp"],
        canonical_storage_path="data/normalized/corporate_actions/",
        canonical_artifact_name="actions.parquet",
        validation_rules=["action_type", "adjustment_factor", "security_id_join"],
        freshness_sla="one business day after source refresh",
        consuming_sleeves=["all backtests", "holdings reconciliation"],
        feature_outputs=["adjustment_factors", "delisting_returns"],
        status="OBSERVE_ONLY",
        known_risks=["double adjustments", "missing merger/spinoff details"],
    ),
    _entry(
        "dataset_freshness",
        "Dataset freshness",
        tier="Tier 1",
        domain="metadata",
        source_type="internal_manifest",
        preferred_source="hydration swarm summary and dataset manifests",
        fallback_source="future canonical validators",
        cost_classification="internal",
        update_frequency="per hydration run",
        expected_latency="same run",
        pit_safe="yes, derived from as-of-dated run metadata",
        required_date_fields=["as_of_date", "latest_source_observation_date", "latest_ingestion_timestamp", "generated_at"],
        canonical_storage_path="data/normalized/freshness/",
        canonical_artifact_name="dataset_freshness.json",
        validation_rules=["status_vocabulary", "catalog_membership", "PIT_status", "artifact_lineage"],
        freshness_sla="generated with every hydration run",
        consuming_sleeves=["operators", "FR-DH validators", "research_data API"],
        feature_outputs=["data_trust_status", "freshness_status", "lineage_status"],
        status="OBSERVE_ONLY",
        known_risks=["stale manifests", "upstream partial data", "missing source observation dates"],
        fr_dh_reference="FR-DH-009",
    ),
    _entry(
        "fundamentals_pit",
        "Fundamentals",
        tier="Tier 2",
        domain="fundamentals",
        source_type="filings_or_vendor_normalized",
        preferred_source="Sharadar SF1 sample after safe fallback probes; filed-date-aware source policy pending",
        fallback_source="SEC companyfacts sample",
        cost_classification="paid_or_existing_tbd",
        update_frequency="quarterly/daily refresh",
        expected_latency="filing date plus ingestion latency",
        pit_safe="yes, required",
        required_date_fields=["fiscal_period_end", "filing_date", "as_of_date", "ingestion_timestamp"],
        canonical_storage_path="data/normalized/fundamentals/",
        canonical_artifact_name="statements.json",
        validation_rules=["filing_date_gate", "restatement_versioning", "period_alignment"],
        freshness_sla="one business day after filing ingestion",
        consuming_sleeves=["Quality", "Value", "Phoenix", "future fundamental sleeves"],
        feature_outputs=["statement_fields", "valuation_inputs"],
        status="OBSERVE_ONLY",
        known_risks=["future restatement leakage", "missing filing dates"],
    ),
    _entry(
        "fundamental_features",
        "Fundamental features",
        tier="Tier 2",
        domain="features",
        source_type="derived",
        preferred_source="FR-DH-005 feature builders",
        fallback_source="none unless approved",
        cost_classification="internal",
        update_frequency="daily after fundamentals refresh",
        expected_latency="after fundamentals validation",
        pit_safe="yes, derived from PIT inputs",
        required_date_fields=["feature_date", "as_of_date", "input_dataset_version"],
        canonical_storage_path="data/features/fundamental_features/",
        canonical_artifact_name="features.parquet",
        validation_rules=["formula_reproducibility", "input_lineage", "missingness_reasons"],
        freshness_sla="same day as input validation",
        consuming_sleeves=["Quality", "Value", "Phoenix"],
        feature_outputs=["value", "quality", "profitability", "leverage", "growth"],
        known_risks=["implicit model change", "universe leakage"],
    ),
    _entry(
        "macro_rates",
        "Macro rates",
        tier="Tier 2",
        domain="macro",
        source_type="public_macro",
        preferred_source="FRED public CSV",
        fallback_source="Treasury public source",
        cost_classification="free",
        update_frequency="daily/monthly by series",
        expected_latency="release lag by series",
        pit_safe="conditional on release dates",
        required_date_fields=["observation_date", "release_date", "as_of_date", "ingestion_timestamp"],
        canonical_storage_path="data/normalized/macro/",
        canonical_artifact_name="macro_rates.json",
        validation_rules=["release_date_availability", "calendar_alignment", "revision_labeling"],
        freshness_sla="one business day after release",
        consuming_sleeves=["Argo", "regime research", "risk diagnostics"],
        feature_outputs=["rate_levels", "rate_changes"],
        status="OBSERVE_ONLY",
        known_risks=["revised history", "release lag", "mixed frequencies"],
    ),
    _entry(
        "yield_curve",
        "Yield curve",
        tier="Tier 2",
        domain="macro",
        source_type="public_rates",
        preferred_source="FRED/Treasury public rates",
        fallback_source="alternate public source",
        cost_classification="free",
        update_frequency="daily",
        expected_latency="same day/T+1",
        pit_safe="yes, if publication time is tracked",
        required_date_fields=["observation_date", "release_date", "as_of_date"],
        canonical_storage_path="data/features/macro_features/",
        canonical_artifact_name="yield_curve.json",
        validation_rules=["curve_point_completeness", "interpolation_policy", "calendar_alignment"],
        freshness_sla="one business day",
        consuming_sleeves=["Argo", "macro regime research"],
        feature_outputs=["slope", "inversion", "term_premium_proxies"],
        status="OBSERVE_ONLY",
        known_risks=["interpolation drift", "holiday gaps"],
    ),
    _entry(
        "credit_spreads",
        "Credit spreads",
        tier="Tier 2",
        domain="macro_credit",
        source_type="public_or_vendor",
        preferred_source="FRED public spread proxies",
        fallback_source="approved credit spread source TBD",
        cost_classification="free_or_paid_tbd",
        update_frequency="daily/monthly by series",
        expected_latency="release lag by series",
        pit_safe="conditional on release dates",
        required_date_fields=["observation_date", "release_date", "as_of_date"],
        canonical_storage_path="data/normalized/macro/",
        canonical_artifact_name="credit_spreads.json",
        validation_rules=["release_date_availability", "missing_series", "unit_consistency"],
        freshness_sla="one business day after release",
        consuming_sleeves=["Argo", "Phoenix", "risk diagnostics"],
        feature_outputs=["spread_levels", "stress_features"],
        status="OBSERVE_ONLY",
        known_risks=["source discontinuities", "revised series"],
    ),
    _entry(
        "vix_volatility_regime",
        "VIX / volatility regime",
        tier="Tier 2",
        domain="volatility",
        source_type="market_index",
        preferred_source="Stooq/CBOE public sample",
        fallback_source="Polygon if configured",
        cost_classification="existing/free_or_paid_tbd",
        update_frequency="daily",
        expected_latency="T+0/T+1",
        pit_safe="yes, if as-of dated",
        required_date_fields=["trade_date", "as_of_date", "ingestion_timestamp"],
        canonical_storage_path="data/normalized/volatility/",
        canonical_artifact_name="vix.json",
        validation_rules=["missing_bars", "stale_date", "calendar_alignment"],
        freshness_sla="next trading day",
        consuming_sleeves=["Phoenix", "Argo", "risk diagnostics"],
        feature_outputs=["vol_regime", "stress_flags"],
        status="OBSERVE_ONLY",
        known_risks=["stale source", "proxy mismatch"],
    ),
    _entry(
        "insider_form4",
        "Insider transactions / Form 4",
        tier="Tier 3",
        domain="insiders",
        source_type="SEC_filing",
        preferred_source="SEC submissions/source filings",
        fallback_source="parsed vendor mirror if approved",
        cost_classification="free_or_paid_tbd",
        update_frequency="daily",
        expected_latency="filing acceptance plus ingestion",
        pit_safe="yes",
        required_date_fields=["transaction_date", "filing_date", "as_of_date", "ingestion_timestamp"],
        canonical_storage_path="data/normalized/insiders/",
        canonical_artifact_name="form4_filings.json",
        validation_rules=["transaction_code_map", "duplicate_amendment_handling", "issuer_join"],
        freshness_sla="one business day after filing",
        consuming_sleeves=["Cassiopeia", "event research"],
        feature_outputs=["insider_buy_sell", "cluster_buying"],
        status="OBSERVE_ONLY",
        known_risks=["noisy transactions", "derivative classification"],
    ),
    _entry(
        "sec_8k_events",
        "SEC 8-K events",
        tier="Tier 3",
        domain="sec_events",
        source_type="SEC_filing",
        preferred_source="SEC submissions/source filings",
        fallback_source="parsed vendor mirror if approved",
        cost_classification="free_or_paid_tbd",
        update_frequency="daily",
        expected_latency="filing acceptance plus ingestion",
        pit_safe="yes",
        required_date_fields=["event_date", "filing_date", "acceptance_timestamp", "as_of_date"],
        canonical_storage_path="data/normalized/sec_events/",
        canonical_artifact_name="eight_k_items.json",
        validation_rules=["item_code_extraction", "accession_join", "amendment_handling"],
        freshness_sla="one business day after filing",
        consuming_sleeves=["Cassiopeia", "event research"],
        feature_outputs=["event_flags", "item_code_features"],
        status="OBSERVE_ONLY",
        known_risks=["event date vs filing date confusion"],
    ),
    _entry(
        "sec_10q_10k_metadata",
        "SEC 10-Q / 10-K filing metadata",
        tier="Tier 3",
        domain="sec_events",
        source_type="SEC_filing",
        preferred_source="SEC submissions/source filings",
        fallback_source="parsed vendor mirror if approved",
        cost_classification="free_or_paid_tbd",
        update_frequency="daily",
        expected_latency="filing acceptance plus ingestion",
        pit_safe="yes",
        required_date_fields=["period_end", "filing_date", "acceptance_timestamp", "as_of_date"],
        canonical_storage_path="data/normalized/sec_events/",
        canonical_artifact_name="filings.json",
        validation_rules=["form_type", "period_alignment", "cik_security_join"],
        freshness_sla="one business day after filing",
        consuming_sleeves=["Cygnus", "Cassiopeia", "fundamentals QA"],
        feature_outputs=["filing_events", "reporting_cadence"],
        status="OBSERVE_ONLY",
        known_risks=["CIK mapping gaps", "amended filings"],
    ),
    _entry(
        "etf_index_constituents",
        "ETF / index constituents",
        tier="Tier 2",
        domain="universe",
        source_type="constituent_reference",
        preferred_source="approved constituent source TBD",
        fallback_source="ETF holdings/public source where feasible",
        cost_classification="free_or_paid_tbd",
        update_frequency="daily/monthly by source",
        expected_latency="source cadence",
        pit_safe="yes, required for historical claims",
        required_date_fields=["effective_date", "as_of_date", "ingestion_timestamp"],
        canonical_storage_path="data/normalized/constituents/",
        canonical_artifact_name="constituents.parquet",
        validation_rules=["membership_date_ranges", "security_id_join", "weight_validation"],
        freshness_sla="source cadence plus one business day",
        consuming_sleeves=["universe research", "Argo", "allocation research"],
        feature_outputs=["membership_flags", "benchmark_exposure"],
        known_risks=["survivorship bias", "current-holdings leakage"],
    ),
    _entry(
        "short_interest",
        "Short interest",
        tier="Tier 3",
        domain="short_interest",
        source_type="exchange_or_vendor",
        preferred_source="approved short interest source TBD",
        fallback_source="FINRA/public source if suitable",
        cost_classification="paid_or_free_tbd",
        update_frequency="biweekly/monthly",
        expected_latency="publication lag by source",
        pit_safe="yes, if settlement/publication dates exist",
        required_date_fields=["settlement_date", "publication_date", "as_of_date"],
        canonical_storage_path="data/normalized/short_interest/",
        canonical_artifact_name="short_interest.parquet",
        validation_rules=["publication_lag", "units", "float_denominator", "stale_checks"],
        freshness_sla="one business day after publication",
        consuming_sleeves=["Phoenix", "risk diagnostics", "future sleeves"],
        feature_outputs=["short_interest_ratio", "squeeze_proxies"],
        known_risks=["reporting lag", "vendor restatements"],
    ),
    _entry(
        "options_iv_open_interest",
        "Options implied volatility / open interest",
        tier="Tier 4",
        domain="options",
        source_type="options_vendor",
        preferred_source="approved options source TBD",
        fallback_source="Polygon/CBOE if configured and legally usable",
        cost_classification="paid_tbd",
        update_frequency="daily/intraday by source",
        expected_latency="source cadence",
        pit_safe="conditional, requires timestamped availability",
        required_date_fields=["quote_date", "expiration_date", "as_of_timestamp", "ingestion_timestamp"],
        canonical_storage_path="data/normalized/options/",
        canonical_artifact_name="options_surface.parquet",
        validation_rules=["surface_completeness", "stale_quotes", "contract_symbology"],
        freshness_sla="source cadence plus one business day",
        consuming_sleeves=["Phoenix", "volatility research", "future options overlays"],
        feature_outputs=["iv_rank", "skew", "open_interest"],
        known_risks=["cost", "contract mapping", "timestamp leakage"],
    ),
    _entry(
        "analyst_estimate_revisions",
        "Analyst estimate revisions",
        tier="Tier 3",
        domain="estimates",
        source_type="estimates_vendor",
        preferred_source="approved estimates source TBD",
        fallback_source="none until approved",
        cost_classification="paid_tbd",
        update_frequency="daily",
        expected_latency="vendor publication lag",
        pit_safe="yes, required",
        required_date_fields=["estimate_date", "revision_date", "publication_date", "as_of_date"],
        canonical_storage_path="data/normalized/estimates/",
        canonical_artifact_name="estimate_revisions.parquet",
        validation_rules=["revision_chronology", "stale_analyst_records", "security_id_join"],
        freshness_sla="one business day after source refresh",
        consuming_sleeves=["Cygnus v1", "Quality", "Value"],
        feature_outputs=["estimate_revision_signals", "surprise_inputs"],
        status="BLOCKED",
        known_risks=["paid dependency", "restatement/availability leakage"],
    ),
    _entry(
        "news_metadata",
        "News metadata",
        tier="Tier 4",
        domain="news",
        source_type="news_vendor_or_public",
        preferred_source="GDELT public sample",
        fallback_source="approved news vendor TBD",
        cost_classification="free_or_paid_tbd",
        update_frequency="daily/intraday",
        expected_latency="source cadence",
        pit_safe="conditional on publication timestamp",
        required_date_fields=["publication_timestamp", "as_of_timestamp", "ingestion_timestamp"],
        canonical_storage_path="data/normalized/news/",
        canonical_artifact_name="news_metadata.parquet",
        validation_rules=["timestamp_checks", "duplicate_detection", "source_attribution"],
        freshness_sla="source cadence plus one business day",
        consuming_sleeves=["Cassiopeia", "event research", "future sleeves"],
        feature_outputs=["news_event_counts", "source_flags"],
        known_risks=["timestamp drift", "syndication duplicates"],
    ),
    _entry(
        "news_sentiment_embeddings",
        "News sentiment / embeddings",
        tier="Tier 4",
        domain="news_features",
        source_type="derived_or_vendor",
        preferred_source="approved model/source TBD",
        fallback_source="none until approved",
        cost_classification="internal_or_paid_tbd",
        update_frequency="daily/intraday after news ingest",
        expected_latency="after news validation",
        pit_safe="conditional on model/input timestamps",
        required_date_fields=["publication_timestamp", "model_run_timestamp", "as_of_timestamp"],
        canonical_storage_path="data/features/news_features/",
        canonical_artifact_name="news_features.parquet",
        validation_rules=["model_version", "input_lineage", "leakage_checks"],
        freshness_sla="after news metadata validation",
        consuming_sleeves=["Cassiopeia", "future alternative-data sleeves"],
        feature_outputs=["sentiment", "topic", "embeddings"],
        known_risks=["model drift", "future-context leakage", "cost"],
    ),
    _entry(
        "institutional_13f",
        "Institutional holdings / 13F",
        tier="Tier 3",
        domain="ownership",
        source_type="SEC_filing",
        preferred_source="SEC 13F source",
        fallback_source="parsed vendor mirror if approved",
        cost_classification="free_or_paid_tbd",
        update_frequency="quarterly",
        expected_latency="filing lag",
        pit_safe="yes",
        required_date_fields=["report_period_end", "filing_date", "as_of_date", "ingestion_timestamp"],
        canonical_storage_path="data/normalized/institutional_holdings/",
        canonical_artifact_name="form13f_holdings.parquet",
        validation_rules=["filing_date_gate", "amendment_handling", "security_id_join"],
        freshness_sla="one business day after filing",
        consuming_sleeves=["Cassiopeia", "ownership research", "risk diagnostics"],
        feature_outputs=["ownership_changes", "crowding_features"],
        known_risks=["delayed filings", "CUSIP mapping", "amendments"],
    ),
    _entry(
        "alternative_datasets",
        "Alternative datasets",
        tier="Tier 4",
        domain="alternative",
        source_type="experimental",
        preferred_source="none approved by default",
        fallback_source="none",
        cost_classification="paid_or_unknown",
        update_frequency="source-specific",
        expected_latency="source-specific",
        pit_safe="no until proven",
        required_date_fields=["source_specific_as_of", "availability_timestamp"],
        canonical_storage_path="data/normalized/alternative/",
        canonical_artifact_name="alternative_<dataset_id>.parquet",
        validation_rules=["source_specific_schema", "PIT_proof", "legal_compliance_review"],
        freshness_sla="source-specific",
        consuming_sleeves=["future sleeves only"],
        feature_outputs=["source_specific_features"],
        status="DRAFT",
        known_risks=["cost", "licensing", "legal", "look-ahead", "weak validation"],
    ),
]


def catalog_entries() -> list[dict[str, Any]]:
    return deepcopy(_CATALOG)


def catalog_entry_by_id(dataset_id: str) -> dict[str, Any]:
    for entry in _CATALOG:
        if entry["dataset_id"] == dataset_id:
            return deepcopy(entry)
    raise KeyError(dataset_id)


def validate_catalog(entries: list[dict[str, Any]]) -> list[str]:
    errors: list[str] = []
    seen: set[str] = set()
    for idx, entry in enumerate(entries):
        dataset_id = str(entry.get("dataset_id") or f"<row {idx}>")
        if dataset_id in seen:
            errors.append(f"duplicate dataset_id: {dataset_id}")
        seen.add(dataset_id)
        for field in REQUIRED_CATALOG_FIELDS:
            if field not in entry:
                errors.append(f"{dataset_id}: missing required field {field}")
            elif entry[field] in (None, "", []):
                errors.append(f"{dataset_id}: empty required field {field}")
    return errors


def catalog_payload(entries: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    actual_entries = entries or catalog_entries()
    return {
        "schema_version": "research_data_catalog_v1",
        "fr_dh_reference": "FR-DH-013",
        "catalog_entry_count": len(actual_entries),
        "required_fields": REQUIRED_CATALOG_FIELDS,
        "entries": actual_entries,
        "catalog_rules": [
            "Every future FR-DH implementation must update the catalog when adding, changing, or retiring a dataset.",
            "No sleeve may depend on an uncataloged dataset after migration to canonical research data.",
            "Production-impacting datasets must include freshness, lineage, validation, and PIT-safety metadata.",
        ],
    }


def write_catalog(path: Path, entries: list[dict[str, Any]] | None = None) -> Path:
    payload = catalog_payload(entries)
    write_json(path, payload)
    return path
