"""Research-only contracts and evidence persistence for Caerus Alpha Lab.

This package deliberately has no dependency on broker, execution, scheduler,
allocation, or production runtime modules.
"""

from .canonical import canonical_hash, canonical_json
from .contracts import (
    ExperimentDesign,
    HypothesisClassification,
    HypothesisManifest,
    Observation,
    RunManifest,
    RunState,
)
from .errors import (
    ContractValidationError,
    EventStoreIntegrityError,
    ProviderNotReadyError,
    ResearchBoundaryError,
)
from .providers import (
    ProviderGateResult,
    ProviderReadiness,
    ProviderRequirement,
    ProviderStatus,
    evaluate_provider_readiness,
    require_provider_ready,
)
from .research_ledger import (
    ChallengeEpoch,
    ExpectedDirection,
    FamilyInference,
    GlobalResearchLedger,
    HoldoutAccess,
    HypothesisFamily,
    IndependentResearchReview,
    InferenceTrack,
    MultipleTestingMethod,
    ResearchPhase,
    ResearchExperiment,
    ResearchRun,
    ResearchRunClass,
    ResearchWave,
    TrialOutcome,
    TrialResult,
    apply_wave_correction,
    benjamini_hochberg,
    benjamini_yekutieli,
    deterministic_access_id,
    deterministic_attempt_id,
    deterministic_trial_id,
    holm_bonferroni,
)
from .store import AppendOnlyJSONLEventStore, EventRecord

__all__ = [
    "AppendOnlyJSONLEventStore",
    "ChallengeEpoch",
    "ContractValidationError",
    "EventRecord",
    "EventStoreIntegrityError",
    "ExperimentDesign",
    "ExpectedDirection",
    "FamilyInference",
    "GlobalResearchLedger",
    "HoldoutAccess",
    "HypothesisFamily",
    "IndependentResearchReview",
    "HypothesisClassification",
    "HypothesisManifest",
    "InferenceTrack",
    "MultipleTestingMethod",
    "Observation",
    "ProviderGateResult",
    "ProviderNotReadyError",
    "ProviderReadiness",
    "ProviderRequirement",
    "ProviderStatus",
    "ResearchBoundaryError",
    "ResearchPhase",
    "ResearchExperiment",
    "ResearchRun",
    "ResearchRunClass",
    "ResearchWave",
    "RunManifest",
    "RunState",
    "TrialOutcome",
    "TrialResult",
    "apply_wave_correction",
    "benjamini_hochberg",
    "benjamini_yekutieli",
    "canonical_hash",
    "canonical_json",
    "deterministic_access_id",
    "deterministic_attempt_id",
    "deterministic_trial_id",
    "evaluate_provider_readiness",
    "holm_bonferroni",
    "require_provider_ready",
]
