"""Research-only contracts and evidence persistence for Caerus Alpha Lab.

This package deliberately has no dependency on broker, execution, scheduler,
allocation, or production runtime modules.
"""

from .canonical import canonical_hash, canonical_json
from .contracts import (
    ExperimentDesign,
    HypothesisClassification,
    HypothesisManifest,
    Observation,
    RunManifest,
    RunState,
)
from .errors import (
    ContractValidationError,
    EventStoreIntegrityError,
    ProviderNotReadyError,
    ResearchBoundaryError,
)
from .providers import (
    ProviderGateResult,
    ProviderReadiness,
    ProviderRequirement,
    ProviderStatus,
    evaluate_provider_readiness,
    require_provider_ready,
)
from .research_ledger import (
    ChallengeEpoch,
    ExpectedDirection,
    FamilyInference,
    GlobalResearchLedger,
    HoldoutAccess,
    HypothesisFamily,
    IndependentResearchReview,
    InferenceTrack,
    MultipleTestingMethod,
    ResearchPhase,
    ResearchExperiment,
    ResearchRun,
    ResearchRunClass,
    ResearchWave,
    TrialOutcome,
    TrialResult,
    apply_wave_correction,
    benjamini_hochberg,
    benjamini_yekutieli,
    deterministic_access_id,
    deterministic_attempt_id,
    deterministic_trial_id,
    holm_bonferroni,
)
from .research_identity import (
    GENESIS_LEDGER_HEAD,
    IdentityActivationEvidence,
    IdentityKey,
    IdentityRegistry,
    IdentityRegistryHistory,
    IdentityRole,
    IdentityStatus,
    IdentityTrustAnchor,
    RegistryRelease,
    ResearchAttestation,
    event_attestation_context_hash,
    migration_plan_attestation_context_hash,
    typed_event_payload_hash,
)
from .projection_export import (
    SIGNED_CLASSIFICATION,
    SIGNED_SCHEMA_VERSION,
    UNSIGNED_CLASSIFICATION,
    UNSIGNED_SCHEMA_VERSION,
    build_signed_projection_export,
    build_unsigned_projection_export,
    projection_export_attestation_context_hash,
)
from .store import AppendOnlyJSONLEventStore, EventRecord

__all__ = [
    "AppendOnlyJSONLEventStore",
    "ChallengeEpoch",
    "ContractValidationError",
    "EventRecord",
    "EventStoreIntegrityError",
    "ExperimentDesign",
    "ExpectedDirection",
    "FamilyInference",
    "GlobalResearchLedger",
    "HoldoutAccess",
    "HypothesisFamily",
    "IndependentResearchReview",
    "HypothesisClassification",
    "HypothesisManifest",
    "IdentityKey",
    "IdentityActivationEvidence",
    "IdentityRegistry",
    "IdentityRegistryHistory",
    "IdentityRole",
    "IdentityStatus",
    "IdentityTrustAnchor",
    "InferenceTrack",
    "MultipleTestingMethod",
    "Observation",
    "ProviderGateResult",
    "ProviderNotReadyError",
    "ProviderReadiness",
    "ProviderRequirement",
    "ProviderStatus",
    "ResearchBoundaryError",
    "ResearchAttestation",
    "SIGNED_CLASSIFICATION",
    "SIGNED_SCHEMA_VERSION",
    "UNSIGNED_CLASSIFICATION",
    "UNSIGNED_SCHEMA_VERSION",
    "build_signed_projection_export",
    "build_unsigned_projection_export",
    "event_attestation_context_hash",
    "migration_plan_attestation_context_hash",
    "projection_export_attestation_context_hash",
    "typed_event_payload_hash",
    "RegistryRelease",
    "ResearchPhase",
    "ResearchExperiment",
    "ResearchRun",
    "ResearchRunClass",
    "ResearchWave",
    "RunManifest",
    "RunState",
    "TrialOutcome",
    "TrialResult",
    "apply_wave_correction",
    "benjamini_hochberg",
    "benjamini_yekutieli",
    "canonical_hash",
    "canonical_json",
    "deterministic_access_id",
    "deterministic_attempt_id",
    "deterministic_trial_id",
    "GENESIS_LEDGER_HEAD",
    "evaluate_provider_readiness",
    "holm_bonferroni",
    "require_provider_ready",
]
